@baseUrl = http://localhost:5158

### 1. تسجيل صحيح - المتوقع: 201 Created
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "fullName": "Ahmed Ali1",
  "email": "ahmed1@test.com",
  "password": "Password123",
  "confirmPassword": "Password123"
}

### 2. نفس الإيميل مرة ثانية - المتوقع: ConflictException
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "fullName": "Ahmed Ali",
  "email": "ahmed@test.com",
  "password": "Password123",
  "confirmPassword": "Password123"
}

### 3. بيانات غلط - المتوقع: ValidationException
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "fullName": "Sara",
  "email": "not-an-email",
  "password": "123",
  "confirmPassword": "456"
}